# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true

logging:
  level: INFO
  format: json
  output: /var/log/app.log

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true

# Optional Development Configuration (can be toggled when needed)
development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false
  cors_enabled: false

# Notification Settings (added from dev branch)
notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
